name: Build and Push GoLang API server Image

on:
  push:
    branches: [main, next]
    paths:
      - 'ui/**'
      - '.github/workflows/docker-api-server.yml'

  workflow_dispatch:
    inputs:
      branch:
        description: 'branch'
        required: true
        
env:
  IMAGE_NAME: pentaledger-api-server

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner
        id: vars
        run: |
          echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ steps.vars.outputs.owner_lc }}/${{ env.IMAGE_NAME }} ./server

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ steps.vars.outputs.owner_lc }}/${{ env.IMAGE_NAME }}
